### ISSUE TITLE
Undefined Columns v3, v4, v5 when deleting role with a domain

### ISSUE THREAD

**Issue by Sir-Kyle-Richardson** [knex/casbin-knex-adapter#1]
Using casbin in node with casbin-knex-adapter (https://github.com/sarneeh/casbin-knex-adapter)

Role and policy in db
![image](https://user-images.githubusercontent.com/8643571/72356772-ce859f00-36b7-11ea-8200-568c4640dfe6.png)

Code snippet being ran:
![image](https://user-images.githubusercontent.com/8643571/72356596-7f3f6e80-36b7-11ea-83f4-bcb95ba16a7f.png)

Invoked with:
```js
{
    userId: 'userId4',
    policyName: 'Delete a role',
    domain: 'organization_1234',
}
```

Error Thrown:
![image](https://user-images.githubusercontent.com/8643571/72356570-75b60680-36b7-11ea-8c57-cbaba5a75d5d.png)

casbin.model.conf:
![image](https://user-images.githubusercontent.com/8643571/72356915-19071b80-36b8-11ea-87f5-05ef87864a33.png)

**Comment by sarneeh** [comment]
Hey @Sir-Kyle-Richardson. I think I won't be able to help you as I'm totally out of time, sorry! 

You can take a look at the implementation and debug it by yourself (it's a single file).

**Comment by hsluoyz** [comment]
@Sir-Kyle-Richardson the images are broken at my side. Can you post some text?

**Comment by Sir-Kyle-Richardson** [comment]
No worries. I'll open a PR with a fix when I get a chance

**Comment by hsluoyz** [comment]
This issue was left unresolved until the repo moved to its new home: knex community

There's also a linked PR here: https://github.com/knex/casbin-knex-adapter/pull/2 , which has code conflicts now. @kibertoad can you please take a look at it?

**Comment by hsluoyz** [comment]
I think @Sir-Kyle-Richardson maybe don't have time right now.

@17bit can you continue the work of PR: https://github.com/knex/casbin-knex-adapter/pull/2 and make a new PR that rebases against master HEAD?

**Comment by kibertoad** [comment]
This should work correctly in latest version, I believe. If someone can still reproduce it with the new version, please reopen!
