### ISSUE TITLE
The `tableName` option is not followed

### ISSUE THREAD

**Issue by code-ape** [knex/casbin-knex-adapter#18]
When initializing the `casbin-knex-adapter` with the `tableName` option the plugin ignores it and still uses `'policies'` as the table name.

**Comment by code-ape** [comment]
Note that this has been resolved in `master` but has not been released yet.

**Comment by kibertoad** [comment]
will publish in a couple of hours

**Comment by kibertoad** [comment]
@code-ape Published in 0.7.2
