### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by kibertoad** [knex/casbin-knex-adapter#3]
Hi! I'm a lead maintainer of knex.js.
Would you be open to the idea of transferring this project to the Knex organization? We would be happy to maintain it going forward. Alternatively, if you prefer to keep the ownership, we could simply contribute our effort, if you wouldn't mind giving us maintainer permissions.

**Comment by sarneeh** [comment]
Hi! Of course! As you can see I don't have too much time even for simple issues like here 😅 So I'm up to transfer this to you guys. Please let me know what organisation name should I transfer this project to and I'll do it 👍

**Comment by kibertoad** [comment]
Appreciate it!
Name is "knex": https://github.com/knex
We don't have npm org, so there you can just give permissions to my user, "kibertoad".

**Comment by sarneeh** [comment]
I added you to the maintainers on npm, but unfortunately cannot transfer the whole repo to the `knex` organisation:
![image](https://user-images.githubusercontent.com/11553624/104238868-e1ad8500-5459-11eb-99a6-a820c0f798cb.png)

**Comment by kibertoad** [comment]
@sarneeh Invited you with appropriate permissions, that should help.

**Comment by kibertoad** [comment]
Also I don't see any changes on https://www.npmjs.com/package/casbin-knex-adapter, wonder if it is cached and takes some time to update.

**Comment by sarneeh** [comment]
@kibertoad Successfully transfered the repo to the knex org.

For the npm, I think I did everything I could:
![image](https://user-images.githubusercontent.com/11553624/104284030-afc80d00-54b1-11eb-8c62-c24e3d29d252.png)

**Comment by kibertoad** [comment]
@sarneeh Thank you! Will get to adding tests and cleanups this week.
