### ISSUE TITLE
Why was this moved under knex organization?

### ISSUE THREAD

**Issue by elhigu** [knex/casbin-knex-adapter#4]
Why was this moved to knex? I'm considering removing the repository since I didn't have rights to transfer ownership back to @sarneeh

**Comment by kibertoad** [comment]
@elhigu Sorry, should have mentioned this! This was my ask, wanted to take over this inactive project and thought that knex would be a better umbrella than myself, since this is a knex thing.

**Comment by kibertoad** [comment]
Are there reasons why you think it would not be a good fit?

**Comment by elhigu** [comment]
I don't know anything if it would be or not. It just did seemed like an abandoned project dumped to knex organization :D
